[package]
name = "teos"
version = "0.2.0"
authors = ["Sergi Delgado Segura <sergi.delgado.s@gmail.com>"]
license = "MIT"
edition = "2018"

[[bin]]
name = "teosd"
path = "src/main.rs"

[dependencies]
# General
libc = "0.2"
rand = "0.8.5"
log = "0.4"
simple_logger = "2.1.0"
structopt = "0.3"
