# API
api_bind = "127.0.0.1"
api_port = 9814
tor_control_port = 9051
onion_hidden_service_port = 9814
tor_support = false

# RPC
rpc_bind = "127.0.0.1"
rpc_port = 8814

# bitcoind
btc_network = "regtest"
btc_rpc_user = "exch"
btc_rpc_password = "goodpass"
btc_rpc_connect = "localhost"
btc_rpc_port = 18443

# Flags
debug = false
deps_debug = false
overwrite_key = false

# General
subscription_slots = 10000
subscription_duration = 4320
expiry_delta = 6
min_to_self_delay = 20
polling_delta = 60

# Internal API
internal_api_bind = "127.0.0.1"
internal_api_port = 50051